### PR TITLE
Implement avahi/mdns client

### PR DESCRIPTION
**Pull request by jbaldwinroberts**
Implement avahi/mdns client so that the device can be discovered as an avahi service

### CODE REVIEW

**Review by mccollam — COMMENTED** [review]
Why the addition of the deviceType parameter to setup()?  It doesn't appear to be referenced anywhere beyond the device ID string... is this just to make the ID more specific?

**Comment by jbaldwinroberts** [comment]
@mccollam not sure how useful it is at the moment but i thought it might be good to have in future. 

The end goal is to share the adapter modules with etcher and this may be useful when etcher needs to discover all devices of a certain type. Another reason is that we should really try to avoid changing this interface as its (potentially) a breaking change so I thought it better to include more info rather than less.

**Comment by mccollam** [comment]
Makes sense; the breaking change there was what concerned me.  If this will be used in the future and avoids breaking when there are more projects using this I'm all for it.

**Review by mccollam — APPROVED** [review]

**Comment by brownjohnf** [comment]
Why the `split` interface? Is there a reason people would want to mess with that?

**Pull request merged**
