### PR TITLE
Move core resin functionality to a separate class

### PR DESCRIPTION
**Pull request by jbaldwinroberts**
Signed-off-by: Joe Roberts <joe@resin.io>

Connects with #6

### CODE REVIEW

**Review by brownjohnf — APPROVED** [review]
Oh, that's beautiful!

**Comment by brownjohnf** [comment]
Next step would be to make this a module we can use directly as an arduino/platformio requirement.

**Review by mccollam — COMMENTED** [review]
Love it, way cleaner!

One question: if the SSID/password is set as a non-const variable, will the Resin constructor fail?  (I can imagine wanting to set these programmatically or even via a keypad on a device.)

**Comment by jbaldwinroberts** [comment]
@mccollam you can pass `char*` to the constructor with no problems :)

**Pull request merged**
